# Generated by Django 3.0.7 on 2022-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0017_stockout_purchased_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
