# Generated by Django 3.0.7 on 2022-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0018_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Parcel', 'Parcel'), ('Quantity', 'Quantity')], default='Quantity', max_length=200, null=True),
        ),
    ]
