# Generated by Django 3.0.7 on 2022-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_product', '0019_auto_20220810_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('کلو گرام', 'کلو گرام'), ('گرام', 'گرام'), ('پارسل', 'پارسل'), ('مقدار', 'مقدار')], default='مقدار', max_length=200, null=True),
        ),
    ]
